// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const SecretMappingsSchema = z.object({
  id: z.string().uuid(),
  key: z.string(),
  value: zodBuffer,
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSecretMappings = z.infer<typeof SecretMappingsSchema>;
export type TSecretMappingsInsert = Omit<z.input<typeof SecretMappingsSchema>, TImmutableDBKeys>;
export type TSecretMappingsUpdate = Partial<Omit<z.input<typeof SecretMappingsSchema>, TImmutableDBKeys>>;
